# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import staging.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, validators=[staging.validators.validate_environment_name])),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('updating', 'Updating'), ('refresing', 'Refreshing'), ('deleting', 'Deleting')], default='creating', max_length=16)),
                ('repository', models.CharField(default='git@github.com:CroceRossaItaliana/jorvik.git', max_length=64)),
                ('branch', models.CharField(default='master', max_length=64)),
                ('sha', models.CharField(blank=True, max_length=40)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS (SSL)')], default='http', max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
