# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='db_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_pass',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_user',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='environment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
