# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0002_auto_20170512_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='db_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='db_pass',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='db_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
