# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0003_auto_20170512_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=128, unique=True)),
                ('allowed_by', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
